# Generated by Django 2.1.7 on 2019-03-24 01:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190310_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUserInfo',
            fields=[
                ('user_id', models.CharField(db_index=True, max_length=300, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 2, 8, 38, 362394, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='todo.LocalUserInfo'),
            preserve_default=False,
        ),
    ]
