# Generated by Django 2.1.7 on 2019-03-24 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190324_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 13, 20, 36, 218052, tzinfo=utc)),
        ),
    ]
